# Generated by Django 4.2.23 on 2025-09-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databasecontroler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserStorage',
            field=models.CharField(default='92e97ab6-bc02-4365-b5e0-6c46d566ab49', max_length=300, verbose_name='Хранилище пользователя'),
        ),
    ]
