# Generated by Django 4.2.23 on 2025-09-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databasecontroler', '0002_alter_user_userstorage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserStorage',
            field=models.CharField(default='d9be8fd2-697b-4c03-86ee-488001075396', max_length=300, verbose_name='Хранилище пользователя'),
        ),
    ]
