# Generated by Django 4.2.23 on 2025-11-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databasecontroler', '0003_alter_user_userstorage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='loadcode',
            field=models.CharField(blank=True, default='b1ed4339-3274-4d68-97d9-cf3be2cc70bf', null=True, verbose_name='Код загрузки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserStorage',
            field=models.CharField(default='957f19a6-2b4d-46b9-bacd-ce8ca58a2903', max_length=300, verbose_name='Хранилище пользователя'),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='FileDescription',
            field=models.TextField(blank=True, max_length=200, verbose_name='Описание файла'),
        ),
    ]
