# Generated by Django 4.2.23 on 2025-11-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databasecontroler', '0004_userfile_loadcode_alter_user_userstorage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='FileCount',
            field=models.CharField(blank=True, null=True, verbose_name='Количество файлов'),
        ),
        migrations.AddField(
            model_name='user',
            name='SizeStorage',
            field=models.CharField(blank=True, null=True, verbose_name='Размер хранилища'),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserStorage',
            field=models.CharField(default='6156d372-d4ce-4d69-9210-853f8a11b4d2', max_length=300, verbose_name='Хранилище пользователя'),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='loadcode',
            field=models.CharField(blank=True, default='f234713d-4ecb-4f68-a4ff-766734043d1a', null=True, verbose_name='Код загрузки'),
        ),
    ]
