# Generated by Django 4.2.23 on 2025-11-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databasecontroler', '0005_user_filecount_user_sizestorage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='FileCount',
            field=models.CharField(blank=True, default=0, null=True, verbose_name='Количество файлов'),
        ),
        migrations.AlterField(
            model_name='user',
            name='SizeStorage',
            field=models.CharField(blank=True, default=0, null=True, verbose_name='Размер хранилища'),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserStorage',
            field=models.CharField(default='6e83faf9-600b-4fef-910a-42e6638b59fc', max_length=300, verbose_name='Хранилище пользователя'),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='loadcode',
            field=models.CharField(blank=True, default='b50ef115-bcac-427f-9b18-5c92924e0d88', null=True, verbose_name='Код загрузки'),
        ),
    ]
