# Generated by Django 4.2.23 on 2025-11-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databasecontroler', '0006_alter_user_filecount_alter_user_sizestorage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='FileCount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество файлов'),
        ),
        migrations.AlterField(
            model_name='user',
            name='SizeStorage',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Размер хранилища'),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserStorage',
            field=models.CharField(default='496d868d-d804-4e83-83ef-512220a8c402', max_length=300, verbose_name='Хранилище пользователя'),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='loadcode',
            field=models.CharField(blank=True, default='2cee352c-a52f-4688-b725-67f035accfe1', null=True, verbose_name='Код загрузки'),
        ),
    ]
