# Generated by Django 4.2.23 on 2025-11-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databasecontroler', '0007_alter_user_filecount_alter_user_sizestorage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='FileCount',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество файлов'),
        ),
        migrations.AlterField(
            model_name='user',
            name='SizeStorage',
            field=models.IntegerField(blank=True, default=0, verbose_name='Размер хранилища'),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserStorage',
            field=models.CharField(default='48e4b669-f0f2-42df-b19e-4a697bbb6df1', max_length=300, verbose_name='Хранилище пользователя'),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='loadcode',
            field=models.CharField(blank=True, default='62b76d66-7174-4aef-b3a1-1db0e247cd7b', null=True, verbose_name='Код загрузки'),
        ),
    ]
